//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento_ged
    {
        public int Id_documento { get; set; }
        public string numero_documento { get; set; }
        public string serie { get; set; }
        public string cnpj { get; set; }
        public string fornecedor { get; set; }
        public string arquivo { get; set; }
    }
}
