//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcao
    {
        public int id_funcao { get; set; }
        public string descricao { get; set; }
        public string pode_aprovar { get; set; }
        public string pode_cadastrar { get; set; }
        public string pode_pagar { get; set; }
    }
}
