//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFe
    {
        public int id_nfe { get; set; }
        public string chave_acesso { get; set; }
        public string cnpj { get; set; }
        public string ie { get; set; }
        public System.DateTime data_emissao { get; set; }
        public string numero { get; set; }
        public string serie { get; set; }
        public System.DateTime data_entrada { get; set; }
        public Nullable<decimal> base_calc_icms { get; set; }
        public Nullable<decimal> valor_icms { get; set; }
        public Nullable<decimal> frete_nfe { get; set; }
        public Nullable<decimal> desconto { get; set; }
        public Nullable<decimal> base_st { get; set; }
        public Nullable<decimal> valor_st { get; set; }
        public Nullable<decimal> ipi { get; set; }
        public decimal valor_produtos { get; set; }
        public decimal total { get; set; }
    }
}
