//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagamento
    {
        public int id_pagamento { get; set; }
        public System.DateTime vencimento { get; set; }
        public string tipo { get; set; }
        public string descricao { get; set; }
        public string fornecedor { get; set; }
        public double valor { get; set; }
        public int id_observacao { get; set; }
        public string observacao { get; set; }
    }
}
