//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_fornecedores
    {
        public int id_rel_fornecedores { get; set; }
        public string cnpj { get; set; }
        public string razao_social { get; set; }
        public string endereco { get; set; }
        public string telefone { get; set; }
        public string ie { get; set; }
        public string email { get; set; }
    }
}
