//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_ged
    {
        public int id_rel_ged { get; set; }
        public int numero_documento { get; set; }
        public string serie { get; set; }
        public string cnpj { get; set; }
        public string fornecedor { get; set; }
        public string arquivo { get; set; }
    }
}
