//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_documentos
    {
        public int id_rel_documentos { get; set; }
        public System.DateTime data_entrada { get; set; }
        public int Nfe_CTe { get; set; }
        public string razao_social { get; set; }
        public double valor { get; set; }
        public string usuario { get; set; }
    }
}
